// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAlvSoXKMc90DgxR1yPAoSaL6Su3WEXzk',
    appId: '1:594398704287:web:fcad30083fa712e6fd28aa',
    messagingSenderId: '594398704287',
    projectId: 'rafeec',
    authDomain: 'rafeec.firebaseapp.com',
    storageBucket: 'rafeec.firebasestorage.app',
    measurementId: 'G-8NFT49HQ3N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCla7s036l9Van7mNS3sqH4fvvHXg41oo0',
    appId: '1:594398704287:android:07077e77f8a5adcefd28aa',
    messagingSenderId: '594398704287',
    projectId: 'rafeec',
    storageBucket: 'rafeec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChx-cG45H-mLVt-jWEsjVhbHLyp5Zj8Ws',
    appId: '1:594398704287:ios:8ab6bf5d32b4786afd28aa',
    messagingSenderId: '594398704287',
    projectId: 'rafeec',
    storageBucket: 'rafeec.firebasestorage.app',
    iosBundleId: 'com.example.projectrafeec1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChx-cG45H-mLVt-jWEsjVhbHLyp5Zj8Ws',
    appId: '1:594398704287:ios:8ab6bf5d32b4786afd28aa',
    messagingSenderId: '594398704287',
    projectId: 'rafeec',
    storageBucket: 'rafeec.firebasestorage.app',
    iosBundleId: 'com.example.projectrafeec1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAlvSoXKMc90DgxR1yPAoSaL6Su3WEXzk',
    appId: '1:594398704287:web:d819b3943b97b4f3fd28aa',
    messagingSenderId: '594398704287',
    projectId: 'rafeec',
    authDomain: 'rafeec.firebaseapp.com',
    storageBucket: 'rafeec.firebasestorage.app',
    measurementId: 'G-BV0E89W8BL',
  );
}
